#version 460
#extension GL_GOOGLE_include_directive : enable         // To be able to use #include
#extension GL_EXT_ray_tracing : require                 // This is about ray tracing
#extension GL_KHR_shader_subgroup_basic : require       // Special extensions to debug groups, warps, SM, ...
#extension GL_EXT_scalar_block_layout : enable          // Align structure layout to scalar
#extension GL_EXT_nonuniform_qualifier : enable         // To access unsized descriptor arrays
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters
#extension GL_EXT_scalar_block_layout : enable          // Usage of 'scalar' block layout

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:enable
#extension GL_EXT_shader_atomic_float: enable

#define RAYTRACING 1

#include "../global.glsl"
#include "../parameters.h"
#include "../settings.h"
#include "../bsdf.glsl"
#include "../shade_state.glsl"
#include "../bindinglayout.h"

layout(location = 0) rayPayloadEXT PtPayload prd;
layout(location = 1) rayPayloadEXT ShadowHitPayload shadow_payload;

float Radiance[25];
float RadianceSum[25];
float Throughput[25];

//  call vulkan API to get collision information.
void ClosestHit(Ray r,float Lmin)
{
	// uint rayFlags = gl_RayFlagsNoneEXT;
	uint rayFlags = gl_RayFlagsOpaqueEXT;
	prd.hitT      = INFINITY;
	traceRayEXT(topLevelAS,   // acceleration structure
				rayFlags,     // rayFlags
				0xFF,         // cullMask
				0,            // sbtRecordOffset
				0,            // sbtRecordStride
				0,            // missIndex
				r.origin,     // ray origin
				Lmin,         // ray min range
				r.direction,  // ray direction
				INFINITY,     // ray max range
				0             // payload (location = 0)
	);
}

//  used in ray tracing pipeline, similar to cloestHit().
bool AnyHit(Ray r, float maxDist)
{
    shadow_payload.isHit = true;      // Asume hit, will be set to false if hit nothing (miss shader)
    shadow_payload.seed  = 0;         // don't care for the update - but won't affect the rahit shader
    uint rayFlags = gl_RayFlagsSkipClosestHitShaderEXT ;
    //   uint rayFlags =   gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsSkipClosestHitShaderEXT;
    //  uint rayFlags = gl_RayFlagsNoneEXT;
    traceRayEXT(topLevelAS,   // acceleration structure
                rayFlags,     // rayFlags
                0xFF,         // cullMask
                0,            // sbtRecordOffset
                0,            // sbtRecordStride
                1,            // missIndex
                r.origin,     // ray origin
                0.011,        // ray min range
                r.direction,  // ray direction
                INFINITY,     // ray max range
                1             // payload layout(location = 1)
  );
  // add to ray contribution from next event estimation
  return shadow_payload.isHit;
}

// wi: in direction; wo: out direction; *World: direction in world coordinates.
bool DirectLighting(vec3 position, vec3 woWorld, ShadeState sstate, int kDepth)
{
  uint matIndex0 = sstate.spectralId * sensorMatrix.waveNum;  // spectral index of band0 for spectralId
  
  vec3 emitterWiWorld = normalize(lightSet.direction);  // sun direction in world coordinates.
  vec3 emitterWi = World2Tangent(sstate.normal, sstate.tangent, sstate.binormal, emitterWiWorld); // sun direction in local coordinates.

  // Judge whether it is exposed to the sun (to avoid self collision, perform small translation of the origin position)
  vec3 ffnormal = dot(sstate.normal, emitterWiWorld) <= 0.0 ? -sstate.normal : sstate.normal;
  vec3 origin = OffsetRay(position, ffnormal);
  Ray shadowRay = Ray(origin, emitterWiWorld);
  bool inLightShadow = AnyHit(shadowRay, OUTER);
  
  // sun distribution
  if(!inLightShadow)
  {
    vec3 wi = emitterWi;
    bool inSameSide = IsSameSide(woWorld, emitterWiWorld, ffnormal);
    float cosTheta = CosThetaTangent(wi);
    float bsdf;
    float bsdf0 = CoefficientOfBSDF(prd.seed); // 1/Pi or -1/Pi

    for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
    {
      int waveInd = sensorWaveInds[kBand].value;
      float wavelength = waveSets[waveInd].wavelength;
      if(wavelength > 50) wavelength = wavelength / 1000.0;
      if(wavelength < 7.5)
      {
        if(!inSameSide)
        {
          bsdf = abs(bsdf0) * spectralMaterials[matIndex0 + kBand].transmittance;
        }
        else
        {
          bsdf = abs(bsdf0) * spectralMaterials[matIndex0 + kBand].reflectance;
        }
        Radiance[kBand] += Throughput[kBand] * lightSet.direct * bsdf * cosTheta;
      }
    }
  }

  // emission distribution
  if(settingxml.isTemperature == 1)
  {
    bool inSameSide = IsSameSide(woWorld, emitterWiWorld, ffnormal);
    for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
    {
      int waveInd = sensorWaveInds[kBand].value;
      float wavelength = waveSets[waveInd].wavelength;
      if(wavelength > 50) wavelength = wavelength/1000.0;
      if(wavelength > 2.5)
      {
        if(!inLightShadow)//sunlit
        {
          
          if(sstate.typeId == TYPE_VEGETATION)
          {
            Radiance[kBand] += Throughput[kBand] * Emission_diff(wavelength, thermalMaterials[sstate.thermalId].sunlitTemperature) 
            * (1 - spectralMaterials[matIndex0 + kBand].reflectance - spectralMaterials[matIndex0 + kBand].transmittance); 
          }
          if(sstate.typeId == TYPE_SOIL || sstate.typeId == TYPE_BUILDING)
          {
            Radiance[kBand] += 1;//sstate.position.y;
            // Radiance[kBand] += Throughput[kBand] * Emission_diff(wavelength, thermalMaterials[sstate.thermalId].sunlitTemperature)
            // * Emissivity_Hapke(1, SSA, POROSITY);
          }
        }
        else
        {
          if(sstate.typeId == TYPE_VEGETATION)
          {
            Radiance[kBand] += Throughput[kBand] * Emission_diff(wavelength, thermalMaterials[sstate.thermalId].shadedTemperature)
            * (1 - spectralMaterials[matIndex0 + kBand].reflectance - spectralMaterials[matIndex0 + kBand].transmittance);
          }
          if(sstate.typeId == TYPE_SOIL || sstate.typeId == TYPE_BUILDING)
          {
            Radiance[kBand] += Throughput[kBand] * Emission_diff(wavelength, thermalMaterials[sstate.thermalId].shadedTemperature)
            * Emissivity_Hapke(1, SSA, POROSITY);
          }
          
        }
      }
    }
  }

  // sky distribution
  if(lightSet.direct < 0.99)
  {
    vec3 emitterWi, scatterWi;
    float emitterBsdf0, emitterPr, emitterBsdf;
    float scatterBsdf0, scatterPr, scatterBsdf;
    vec3 upWorld = {0, 1, 0};
    SampleBSDF(prd.seed, emitterWi, emitterBsdf0, emitterPr);

    float emitteringLi = lightSet.diffuse * M_1_OVER_PI;
    vec3 emitterWiWorld = Tangent2World(sstate.normal, sstate.tangent, sstate.binormal, emitterWi);
    emitterWiWorld = dot(upWorld, emitterWiWorld) <= 0.0 ? -emitterWiWorld : emitterWiWorld;

    bool inSameSide = IsSameSide(woWorld, emitterWiWorld, ffnormal);
    origin = OffsetRay(position, dot(emitterWiWorld, ffnormal) > 0 ? ffnormal : -ffnormal);
    Ray skyRay = Ray(origin, emitterWiWorld);
    bool inSkyShadow = AnyHit(skyRay, OUTER);

    if(!inSkyShadow)
    {
      for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
      {
        int waveInd = sensorWaveInds[kBand].value;
        float wavelength = waveSets[waveInd].wavelength;
        if(wavelength > 50) wavelength = wavelength/1000.0;
        if(wavelength < 7.5)
        {
          if(emitterPr > EPSION)
          {
            if(emitteringLi > EPSION)
            {
              vec3 wi = emitterWi;
              float cosTheta = CosThetaTangent(wi);
              SampleBSDF(prd.seed, scatterWi, scatterBsdf0, scatterPr);
              float weight = 0.5;
              if(inSameSide)
              {
                emitterBsdf = abs(emitterBsdf0) * spectralMaterials[matIndex0 + kBand].reflectance;
              }
              else
              {
                emitterBsdf = abs(emitterBsdf0) * spectralMaterials[matIndex0 + kBand].transmittance;
              }
              Radiance[kBand] += Throughput[kBand] * (emitteringLi * cosTheta * emitterBsdf * weight)/emitterPr;
            }
          }
        }
      }
    }

    if(emitterPr != 0.0)
    {
      SampleBSDF(prd.seed, scatterWi, scatterBsdf0, scatterPr);
      if(scatterPr > EPSION)
      {
        float scatteringLi = lightSet.diffuse * M_1_OVER_PI;
        vec3 scatterWiWorld = Tangent2World(sstate.normal, sstate.tangent, sstate.binormal, scatterWi);
        scatterWiWorld = dot(upWorld, scatterWiWorld) <= 0.0 ? -scatterWiWorld : scatterWiWorld;
        inSameSide = IsSameSide(woWorld, scatterWiWorld, ffnormal);

        origin = OffsetRay(position, dot(scatterWiWorld, ffnormal) > 0 ? ffnormal : -ffnormal);
        skyRay = Ray(origin, scatterWiWorld);
        inSkyShadow = AnyHit(skyRay, OUTER);

        if(!inSkyShadow)
        {
          for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
          {
            float wavelength = waveSets[kBand].wavelength/1000.0;
            if(wavelength < 7.5)
            {
              vec3 wi = scatterWi;
              float cosTheta = CosThetaTangent(wi);
              float weight = PowerHeuristic(scatterPr, emitterPr);

              if(inSameSide)
              {
                scatterBsdf = abs(scatterBsdf0) * spectralMaterials[matIndex0 + kBand].reflectance;
              }
              else
              {
                scatterBsdf = abs(scatterBsdf0) * spectralMaterials[matIndex0 + kBand].transmittance;
              }
              Radiance[kBand] += Throughput[kBand] * (scatteringLi * cosTheta * scatterBsdf * weight)/scatterPr;
            }
          }
        }
      }

    }
  }

  return true;
}

bool InDirectLighting(vec3 position, vec3 woWorld, ShadeState sstate, int kDepth, out vec3 wiWorld)
{
  float bsdf0, pr;
  vec3 wi;
  vec3 upWorld = {0, 1, 0};
  SampleBSDF(prd.seed, wi, bsdf0, pr);

  float cosTheta = CosThetaTangent(wi);
  uint matIndex0 = sstate.spectralId * sensorMatrix.waveNum;

  int ifrefl = 1;
  for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
  {
    float bsdf, pathThroughput;
    if(spectralMaterials[matIndex0 + kBand].transmittance < EPSION)
    {
      // bsdf = abs(bsdf0) * spectralMaterials[matIndex0 + kBand].reflectance;
      if(sstate.typeId == TYPE_VEGETATION)
      {
        bsdf = abs(bsdf0) * spectralMaterials[matIndex0 + kBand].reflectance;
      }
      if(sstate.typeId == TYPE_SOIL || sstate.typeId == TYPE_BUILDING)
      {
        bsdf = abs(bsdf0) * (1 - Emissivity_Hapke(1, SSA, POROSITY));
      }
      pathThroughput = bsdf * cosTheta;
    }
    else
    {
      if(bsdf0 < 0)
      {
        bsdf = -bsdf0 * spectralMaterials[matIndex0 + kBand].transmittance;
        ifrefl = 0;
      }
      else
      {
        bsdf = bsdf0 * spectralMaterials[matIndex0 + kBand].reflectance;
      }
      pathThroughput = 2.0 * bsdf * cosTheta;
    }

    if(pr > EPSION) Throughput[kBand] *= (pathThroughput/pr);
    else Throughput[kBand] *= (pathThroughput);
  }

  wiWorld = Tangent2World(sstate.normal, sstate.tangent, sstate.binormal, wi);
  bool inSameSide = IsSameSide(woWorld, wiWorld, sstate.normal);
  if(sstate.typeId == TYPE_VEGETATION)
  {
    if((inSameSide == false) && (ifrefl == 1)) wiWorld = -wiWorld;
    if((inSameSide == true) && (ifrefl == 0)) wiWorld = -wiWorld;
  }
  if(sstate.typeId == TYPE_SOIL || sstate.typeId == TYPE_BUILDING)
  {
    if(inSameSide == false) wiWorld = -wiWorld;
  }

  // if(sstate.typeId == TYPE_SOIL)
  // {
  //   vec3 wo = World2Tangent(sstate.normal, sstate.tangent, sstate.binormal, woWorld);
  //   bool inLocalSameSide = IsSameSide(wo, wi, sstate.localNormal);
  //   if(inLocalSameSide == false) wi = -wi;
  //   wiWorld = Tangent2World(sstate.normal, sstate.tangent, sstate.binormal, wi);
  // }
  // else
  // {
  //   wiWorld = Tangent2World(sstate.normal, sstate.tangent, sstate.binormal, wi);
  //   bool inSameSide = IsSameSide(woWorld, wiWorld, sstate.normal);
  //   if((inSameSide == false) && (ifrefl == 1)) wiWorld = -wiWorld;
  //   if((inSameSide == true) && (ifrefl == 0)) wiWorld = -wiWorld;
  // }

  return true;
}

// Cyclic iteration of ray collisions.
bool PathTrace(Ray r)
{
  for(int kDepth = 0; kDepth < settingxml.maxDepth; kDepth++)
  {
    // Russian roulette termination.
    if(kDepth >= 10)
    {
      float maxPathThroughput = 0;
      for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
      {
        if(Throughput[kBand] > maxPathThroughput)
        {
          maxPathThroughput = Throughput[kBand];
        }
      }
      float pCont = 1 - maxPathThroughput;
      pCont = max(pCont, 0.05);
      if(rand(prd.seed) < pCont) break; // no change
      // set all throughput /= (1 - P)
      for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
      {
        Throughput[kBand] /= (1 - pCont);
      }
    }

    ClosestHit(r, 0.0001);

    // if hit outside the scene(PS: the started data segment is 0.)
    if(prd.hitT == INFINITY)
    {
      if(kDepth == 0) return false; // hit nothing.
      for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
      {
        int waveInd = sensorWaveInds[kBand].value;
        float wavelength = waveSets[waveInd].wavelength;  // units set to nanometers.
        if(wavelength > 50) wavelength = wavelength/1000.0;
        if(wavelength > 2.5)  // for wavelength > 2500nm, added sky temperature.
        {
          Radiance[kBand] += 0;
          // Radiance[kBand] += Throughput[kBand] * Emission_diff(wavelength, lightSet.skyTemperature);
        }
      }
      return true;
    }


    ShadeState sstate = GetShadeState(prd);
    vec3 position = sstate.position;
    vec3 normal = sstate.normal;
    vec3 woWorld = sstate.position - sstate.lastPosition;
    vec3 wiWorld = vec3(0, 1, 0);

    DirectLighting(position, woWorld, sstate, kDepth);
    InDirectLighting(position, woWorld, sstate, kDepth, wiWorld);

    vec3 ffnormal = sstate.normal;
    r.direction = wiWorld;
    r.origin = OffsetRay(sstate.position, dot(wiWorld, ffnormal) > 0 ? ffnormal : -ffnormal);

    // for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
    // {
    //   int waveInd = sensorWaveInds[kBand].value;
    //   float wavelength = waveSets[waveInd].wavelength;  // units set to nanometers.
    //   if(wavelength > 50) wavelength = wavelength/1000.0;
    //   if(wavelength > 2.5)  // for wavelength > 2500nm, added sky temperature.
    //   {
    //     Radiance[kBand] = wiWorld.z;
    //     //Radiance[kBand] += Throughput[kBand] * Emission_diff(wavelength, lightSet.skyTemperature);
    //   }
    // }
  }
  return true;
}

void SamplePixel(int kSample, ivec2 imageCoords, ivec2 imageResolution)
{
  // For each sampling of a pixel, its inital postion and direction are randomly generated.
  // subPixel_jitter is the random disturbance variation.
  vec2 subPixel_jitter = kSample == 0 ? vec2(0.5f, 0.5f) : vec2(rand(prd.seed), rand(prd.seed));
  const vec2 pixelCenter = vec2(imageCoords) + subPixel_jitter;
  const vec2 inUV = pixelCenter/vec2(imageResolution.xy);
  vec2 d = inUV * 2.0 - 1.0;  // this scope is limited to [-1,1]
  vec4 origin = sensorMatrix.viewInverse * vec4(0, 0, 0, 1);    // ray origin.
  vec4 target = sensorMatrix.projInverse * vec4(d.x, d.y, 1, 1);
  vec4 direction = sensorMatrix.viewInverse * vec4(normalize(target.xyz), 0); // ray direction

  // Parallel projection and central projection. ?if use?, can removed????
  vec3 focalPoint = sensorMatrix.focalDist * direction.xyz;
  float cam_r1 = rand(prd.seed) * M_TWO_PI;
  float cam_r2 = rand(prd.seed) * sensorMatrix.aperture;
  vec4 cam_right = sensorMatrix.viewInverse * vec4(1, 0, 0, 0);
  vec4 cam_up = sensorMatrix.viewInverse * vec4(0, 1, 0, 0);
  vec3 randomAperturePos = (cos(cam_r1) * cam_right.xyz + sin(cam_r1) * cam_up.xyz) * sqrt(cam_r2);
  vec3  finalRayDir       = normalize(focalPoint - randomAperturePos);

  // Every band radiance value is initialized to 0.
  for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
  {
    Radiance[kBand] = 0;
    Throughput[kBand] = 1.0;
  }

  Ray ray = Ray(origin.xyz, direction.xyz);
  PathTrace(ray);

}

void main()
{
	uint64_t start = clockRealtimeEXT();  // Debug - Heatmap
	ivec2 imageRes    = settingxml.imageSize;
  ivec2 imageCoords = ivec2(gl_LaunchIDEXT.xy);
	int bufferId = sensorMatrix.waveNum * (imageCoords.y * imageRes.x + imageCoords.x );
  prd.seed = initRandom(gl_LaunchSizeEXT.xy, gl_LaunchIDEXT.xy, settingxml.frame);

	// Average value after multiple sampling.
  // set RandianceSum = 0; accumulation over sampling; average the accumulation.
	for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
  {
    Radiance[kBand] = 0.0;
    RadianceSum[kBand] = 0.0;
  }

  int validNum = 0;
  for(int kSample = 0; kSample < settingxml.maxSample; kSample++)
  {
    SamplePixel(kSample, imageCoords, imageRes);

    bool isValid = false;
    for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
    {
      if(Radiance[kBand] > EPSION)
      {
        RadianceSum[kBand] += Radiance[kBand];
        isValid = true;
      }
    }

    if(isValid) validNum += 1;
  }
  // Do accumulation over sample
	for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
	{
    if(validNum == 0) Radiance[kBand] = 0;
    if(validNum > 0) Radiance[kBand] = RadianceSum[kBand]/validNum;
	}

	// Write result into _bufferstorage(layout buffer)
	for(int kBand = 0; kBand < sensorMatrix.waveNum; kBand++)
	{
		float value = Radiance[kBand];
		atomicStore(outImage[bufferId + kBand], value, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsRelease);
	}

}
