#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:require
#extension GL_EXT_shader_atomic_float: require 

#define VOXEL_LST_BIND_ININDEX
#define VOXELLST 1

#include "../bindinglayout.h"
#include "../parameters.h"
#include "../global.glsl"
#include "../settings.h"
#include "../functions.glsl"
#include "../nanovdb_info.glsl"
#include "../shade_state_voxel.glsl"

PtPayload        prd;
ShadowHitPayload shadow_payload;

#include "../traceray_comp.glsl"

layout(local_size_x = GROUP_SIZEX) in;
#define MAXBAND    25
#define NUM_VNIR 2001 
#define NUM_BAND 2002

float GammaR[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];
float GammaT[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];
// from solar direction to selected direction;
float GammaSR[DIFFUSE_ANGLE_NUM];
float GammaST[DIFFUSE_ANGLE_NUM];

// calculate the scattering phase function from solar angle to N angles.
void Scattering_phase_function_solar_diffuse()
{
    vec3 directioni = normalize(lightSet.direction);

    // directioni = vec3(0,1,0);
    for(int jangle = 0; jangle < DIFFUSE_ANGLE_NUM; jangle++)
    {
        vec3 directionj = normalize(DIFFUSE_DIRECTIONS[jangle]);
        vec2 gamma = scattering_phase_function_direct_XZY_paper(directioni, -directionj);
        GammaSR[jangle] = gamma.x;
        GammaST[jangle] = gamma.y;
    }
}

// calculate the scattering phase function from N angles to N angles.
void Scattering_phase_function_diffuse()
{
    for(int iangle = 0; iangle < DIFFUSE_ANGLE_NUM; iangle++)
    {
        vec3 directioni = normalize(DIFFUSE_DIRECTIONS[iangle]);
        for(int jangle = 0; jangle < DIFFUSE_ANGLE_NUM; jangle++)
        {
            vec3 directionj = normalize(DIFFUSE_DIRECTIONS[jangle]);
            vec2 gamma = scattering_phase_function_direct_XZY_paper(directioni, -directionj);
            GammaR[iangle * DIFFUSE_ANGLE_NUM + jangle] = gamma.x;
            GammaT[iangle * DIFFUSE_ANGLE_NUM + jangle] = gamma.y;
        }
    }
}

// calculate the diffuse term.
bool voxel_raytracing_diffuse(vec3 voxelPos0, uint bufferId0, NanoVDBLink nanoVDBLink,
 int kiter,int kband,float Esun,float Esky,int stepnum)
{

  float G,density;
  float scale = setting.scale;
  vec3 semiRange = vec3(floor(setting.voxelSize.x/2.0+0.5),0,floor(setting.voxelSize.z/2.0+0.5));
  // semiRange = vec3(0,0,0);
  // i:induced direction for the selected voxel; 0 original
  // j:induced direction for the traveled voxel;
  // s:solar direction
  vec3 directioni,directioni0,directionj,directionj0;
  vec3 directions = normalize(lightSet.direction);
  float cosSolar = abs(normalize(lightSet.direction).y);
  int bufferId,alignBufferId;
  uint spectralId,thermalId,canopyId;
  vec2 gammart;
  float alpha_voxel,alpha_toSolar,alpha_toVoxel;
  uint typeId,meshId;
  uint instanceId,lastInstanceId,alignInstanceId;
  uint bufferIdPlus0;
  ivec3 voxelId,alignVoxelId;
  float pl_toSolar,pl_toVoxel,refl,trans,emis,gamma,wavelength;
  float sunlitTemperature,sunlitRadiance,shadedTemperature,shadedRadiance,thermalRadiance;
  ivec3 voxelRes = ivec3(setting.voxelSize);

  InstanceLink instanceLink;
  MeshLink meshLink;
  Canopy canopy;


  ivec3 voxelId0 = voxelLinks[bufferId0].voxelId;
  uint instanceId0 = voxelLinks[bufferId0].instanceId;
  uint meshId0 = instanceLinks[instanceId0].meshId;
  uint typeId0 = meshLinks[meshId0].type;
  
  bool isvegfirst = true;
  ////////////////////////////////////////////////////////
  //  Iteration in difuse angle
  ////////////////////////////////////////////////////////
  for(uint iangle = 0; iangle < DIFFUSE_ANGLE_NUM; iangle++)
  {
    directioni0 = DIFFUSE_DIRECTIONS[iangle];
    directioni = normalize(directioni0);
    Ray ray = Ray(voxelPos0, directioni);
    alpha_toSolar = 1.0;
    alpha_toVoxel = 1.0;
	  voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced = 0.0;

    /////////////////////////////////////////////////////
    /// Iteration in travel step
    /////////////////////////////////////////////////////
    int kstep = 0;
    vec3 ffnormal;
    for(kstep = 0;kstep<=setting.maxStep;kstep++)
    //  for(kstep = 0;kstep<=5;kstep++)
    { 
      alpha_voxel = 1.0;
      ClosestHit(ray,0.001);
      if(prd.hitT == INFINITY)
      {
        //////////////////////////////
        /// Atmospheric case
        /////////////////////////////

        // add save the sky contribution
        // sky contribution: lightSet.Rli*waveSets[kband].diffuse*0.001
        if(directioni0.y >= 0)
        {
           float skyrad = alpha_toVoxel*Esky / PI;
           //skyrad = 1000;
          //skyrad = 0.5;
          uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
          atomicAdd(voxelRads[index].induced,
              skyrad,
              gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
        }
        alpha_toVoxel = 0.001;
        break;
      }

      //break;
      // get hit information
      ShadeState sstate = GetShadeState(prd);

      // get voxelId and alignVoxelId
      voxelId = getVoxelIdSemi(sstate.position,semiRange,scale,directioni,alignVoxelId);
      // get bufferId and alignBufferId;
      // if bufferId/alignBufferId = -1, this voxel is blank;
      bufferId = nanovdbGet(nanoVDBLink,voxelId);
      alignBufferId = nanovdbGet(nanoVDBLink,alignVoxelId);
      //////////////////////////////
      /// Trubid case
      /////////////////////////////
      if(bufferId >= 0)
      {
          // a valid voxel and get voxel information 
          // such as instanceId, typeId, spectralId, thermalId, canopyId
          instanceId = voxelLinks[bufferId].instanceId;
          meshId = instanceLinks[instanceId].meshId;
          meshLink = meshLinks[meshId];
          canopyId = meshLink.canopyId;
          typeId = meshLink.type;
          spectralId = meshLink.spectralId;
          thermalId = meshLink.thermalId;
          uint spectralIdBase = spectralId*NBAND;
          //////////////////////////////
          /// Trubid case
          /////////////////////////////
          if(typeId == TYPE_VEGETATION)
          {
            G = canopies[canopyId].G;
            // density determined by mesh/isntance or pixel scale?
            if(setting.islad < 1){
                density = canopies[canopyId].density;
            }else{         
                uint surf1DId = SurfFlatten(voxelId, voxelRes);
                density = lads[surf1DId]; 
            }
            float pathLength = Vector2Distance(sstate.position - sstate.lastPosition);
            alpha_voxel = exp(-density * G * pathLength * scale);
            alpha_toSolar = voxelDirs[bufferId].solar;

            // get the phase function for solar direction to induced direction 
            gammart.x = GammaSR[iangle];
            gammart.y = GammaST[iangle];
            sunlitTemperature = voxelTempes[bufferId].sunlit;
            shadedTemperature = voxelTempes[bufferId].shaded;
            /////////////////////////////////////////////////////
            /// Iteration in BAND
            /////////////////////////////////////////////////////

            // // THERMAL
            // wavelength = atomConds[kband].wavelength;
            // sunlitRadiance = Planck(wavelength,sunlitTemperature)*stepnum;
            // shadedRadiance = Planck(wavelength,shadedTemperature)*stepnum;
            // thermalRadiance = (1-alpha_toSolar)*shadedRadiance + alpha_toSolar*sunlitRadiance;

            // SPECTRAL
            trans = spectralMaterials[spectralId*NBAND+kband].transmittance;
            refl = spectralMaterials[spectralId*NBAND+kband].reflectance;
            emis = 1 - trans - refl;
            // float gamma = abs(gammart.x)*(refl + trans) + abs(gammart.y)*trans;  
            float gamma = (gammart.x)*(refl + trans) + (gammart.y)*trans;  
            gamma = clamp(gamma,0,1);
            float radiance = 0;
           
            //////////////////////////////
            // emitter
            /////////////////////////////
            // thermalRadiance = 100;
            //   radiance+= (thermalRadiance*(1-alpha_voxel)*emis* alpha_toVoxel);
            // radiance = shadedTemperature;
            //////////////////////////////
            /// Solar 
            /////////////////////////////
            radiance += (alpha_toSolar * gamma * Esun/cosSolar * alpha_toVoxel *(1-alpha_voxel));  
            // radiance += (alpha_toSolar * gamma * Esun * alpha_toVoxel *(1-alpha_voxel));  
            //////////////////////////////
            /// Multiple case
            /////////////////////////////
            float radianceD = 0;
            if(kiter > 0)
            {
              int effeNum = 0;
              for(int jangle=0;jangle<DIFFUSE_ANGLE_NUM;jangle++)
              {
                  float radiancej = abs(voxelRads[bufferId*DIFFUSE_ANGLE_NUM+jangle].cumulated);
                  if(radiancej<EPSION_3) continue;
                  directionj0 = (DIFFUSE_DIRECTIONS[jangle]);
                  gammart.x = GammaR[iangle*DIFFUSE_ANGLE_NUM+jangle];
                  gammart.y = GammaT[iangle*DIFFUSE_ANGLE_NUM+jangle];
                  gamma =   (gammart.x)*(refl + trans)+ (gammart.y)*trans;  
                  gamma = clamp(gamma,0,1);
                  radianceD= radianceD + abs(radiancej * gamma* alpha_toVoxel*abs(1-alpha_voxel));  
                  effeNum ++;
              }
              if (effeNum ==0) effeNum = 1;
              radianceD = (radianceD / effeNum);
              // radianceD = (radianceD / DIFFUSE_ANGLE_NUM);
            }
            radiance += radianceD;
            //////////////////////////////
            /// Save back
            /////////////////////////////
            atomicAdd(voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced,radiance,
                gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
            alpha_toVoxel = alpha_toVoxel * alpha_voxel;
            if(alpha_toVoxel < 0.01) break; 
          }  
      }// if vegetation


      if (alignBufferId >= 0)
      {
        //////////////////////////////
        /// facet case
        /////////////////////////////
        instanceId = voxelLinks[alignBufferId].instanceId;
        meshId = instanceLinks[instanceId].meshId;
        typeId = meshLinks[meshId].type;
        canopyId = meshLinks[meshId].canopyId;
        spectralId = meshLinks[meshId].spectralId;
        thermalId = meshLinks[meshId].thermalId;

        if(typeId == TYPE_VEGETATION){
          //// do nothing
          // ray = Ray(sstate.position,directioni);
          // ffnormal  = sstate.normal;
          // ray.origin = OffsetRay(ray.origin, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
          // continue;
        }
       
        if(typeId == TYPE_BUILDING)
        {
          int faceId = getFaceIdSimple(sstate.position,semiRange,alignVoxelId);
          alignBufferId = alignBufferId + faceId;
        }

        if (typeId == TYPE_BUILDING || typeId == TYPE_SOIL){
          uint spectralIdBase = spectralId*NBAND;
      
          alpha_toSolar = voxelDirs[alignBufferId].solar;
          vec3 wo = directioni;  // FROM SELECTED VOXEL OUT TO HIT FACET  
          vec3 wi = lightSet.direction; // FROM SELECTED VOXEL OUT TO SOLAR
          vec3 ffnormal = sstate.normal;
          bool inSameSides = IsSameSide(wo,wi,ffnormal);
          
          float radiance=0;
          // // THERMAL
          // sunlitTemperature = voxelTempes[alignBufferId].sunlit;
          // shadedTemperature = voxelTempes[alignBufferId].shaded;
          // wavelength = atomConds[kband].wavelength;
          // sunlitRadiance = Planck(wavelength,sunlitTemperature)*stepnum;
          // shadedRadiance = Planck(wavelength,shadedTemperature)*stepnum;
          // thermalRadiance = (1-alpha_toSolar)*shadedRadiance + alpha_toSolar*sunlitRadiance;
          // SPECTRAL
          trans = spectralMaterials[spectralId*NBAND+kband].transmittance;
          refl = spectralMaterials[spectralId*NBAND+kband].reflectance;
          emis = 1 - trans - refl;
          //////////////////////////////
          /// Multiple case
          /////////////////////////////
          if(kiter > 0)
          {
            int effeNum = 0;
            float pdf = 0.0;
            for(int jangle=0;jangle<DIFFUSE_ANGLE_NUM;jangle++)
            {
                directionj0 = (DIFFUSE_DIRECTIONS[jangle]);
                bool inSameSide = IsSameSide(directioni,directionj0,ffnormal);
                if(!inSameSide) continue;
                float radiancej = abs(voxelRads[alignBufferId*DIFFUSE_ANGLE_NUM+jangle].cumulated);
                if(radiancej < EPSION_3) continue;

                directionj = normalize(directionj0);
                radiance= radiance + radiancej * abs(directionj.y) * refl * abs(alpha_toVoxel); 
                pdf += abs(directionj.y);
                effeNum ++;
            }
            if (effeNum ==0) effeNum = 1;
            if (pdf ==0) pdf = effeNum;
            radiance = radiance / pdf;
            // radiance = abs(radiance/DIFFUSE_ANGLE_NUM/2.0);
          }
          
          ////////////////////////////////
          // SOLAR CASE
          ///////////////////////////////
          if(inSameSides)
          {
            radiance += (refl/ PI * Esun  * alpha_toSolar * alpha_toVoxel);
          }
          // ////////////////////////////////
          // //emitter
          // ////////////////////////////////
          //   radiance+= (thermalRadiance * emis * alpha_toVoxel);
          //////////////////////////////
          /// Save back
          /////////////////////////////
      
          atomicAdd(voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced,radiance,
              gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);

          alpha_toVoxel = 0;
          break;
        }
        
      }// if facet


      ray = Ray(sstate.position,directioni);
      ffnormal  = sstate.normal;
      ray.origin = OffsetRay(ray.origin, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
    }

    if((kstep >= setting.maxStep) && (alpha_toVoxel > EPSION_2))
    {
        float skyrad = alpha_toVoxel*Esky/PI;
        //skyrad = 0.5;
        uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
        atomicAdd(voxelRads[index].induced,
            skyrad,
            gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    }
  }
  return false;
}

void main()
{
  //------------------------------------------------------------
  // Initialization for the position and SSBO index
  //------------------------------------------------------------
  // get bufferId, voxelId, instanceId and typeId
  uint bufferId0 = uint(gl_GlobalInvocationID.x);
  ivec3 voxelId0 = voxelLinks[bufferId0].voxelId;
  if(voxelLinks[bufferId0].isValid==0) return;
  // Get nanoVDBLink: from voxelId to bufferId
  NanoVDBLink nanoVDBLink = nanovdbInit();
  uint instanceId = voxelLinks[bufferId0].instanceId;
  uint meshId = instanceLinks[instanceId].meshId;
  uint typeId0 = meshLinks[meshId].type;
  uint spectralId = meshLinks[meshId].spectralId;
  uint spectralIdBase = spectralId * NBAND;

  float Rin = ubom.meteo.Rin;               // shortwave
  float Rli = ubom.meteo.Rli;               // longwave

		uint	canopyId = meshLinks[meshId].canopyId;

  int faceId = voxelLinks[bufferId0].faceId;

  // get center position of a voxel
  float scale = setting.scale;
  vec3 semiRange = vec3(floor(setting.voxelSize.x/2.0+0.5),0,floor(setting.voxelSize.z/2.0+0.5));


  // from vbd space to vk space
  vec3 voxelPos0 = vec3(voxelId0.x- semiRange.x,
                        voxelId0.y,
                        voxelId0.z -semiRange.z); 
  getFacetIdPos(faceId,  voxelPos0);
  

  // calculate the scattering phase function from solar angle to N angles.
  Scattering_phase_function_solar_diffuse();

  // calculate the scattering phase function from N angles to N angles.
  Scattering_phase_function_diffuse();

  // set the diffuse in VNIR
  voxelNetRads[bufferId0].diffuseVrad = 0;

  // maxIteration is scattering times.
  // induced in primary time is calculated at solar file.
  if(setting.maxIteration > 1)
  {

      int kband_start = 0, kband_end = 0, kband_center;
      // int kstep = setting.bandTstep;
      int kstep = 50;
      int step_num = int(NUM_VNIR/kstep)+1;
      
      float EEsun = 0,EEsky =0;
      for(int kbandi = 0; kbandi <step_num; kbandi++)
      {
          kband_start = kbandi*kstep;
          kband_end = kband_start+kstep;

          if(kband_start > NUM_VNIR) break;
          if(kband_end > NUM_VNIR) kband_end = NUM_VNIR;
          kband_center = int((kband_end + kband_start)/2);
          float Esun = 0, Esky = 0, wavelengthwidth = 0;
          float temp=0;
          for(int kbandj = kband_start; kbandj < kband_end; kbandj++)
          {
            if (kbandj == 0)
                wavelengthwidth = atomConds[1].wavelength - atomConds[0].wavelength;
            else
                wavelengthwidth = atomConds[kbandj].wavelength - atomConds[kbandj - 1].wavelength;
              Esun = Esun + Rin*atomConds[kbandj].direct*0.001;
              Esky = Esky + Rin*atomConds[kbandj].diffuse*0.001;
              temp = temp +1;
          }

          for(int kiter=0;kiter< 5;kiter++)
          {
              voxel_raytracing_diffuse(voxelPos0, bufferId0, nanoVDBLink, kiter,kband_center,Esun,Esky,kstep);
              groupMemoryBarrier();  
              barrier();

              for(uint iangle=0;iangle < DIFFUSE_ANGLE_NUM;iangle++)
              {
                  uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
                  voxelRads[index].cumulated = voxelRads[index].induced;
              }
          }// for iteration

    
          float rads = 0, radtemp = 0, absorb = 1.0;
          
          //-------------------------------------------------------
          // for twince receive and twince emit, but it not work
          // using effeNum replace this function
          //--------------------------------------------------------
          absorb = 1 - spectralMaterials[spectralIdBase + kband_center].transmittance -
                  spectralMaterials[spectralIdBase + kband_center].reflectance;

          if (typeId0 == TYPE_SOIL || typeId0 == TYPE_BUILDING)
          {
              // iteration in diffuse
              int effeNum = 0;
              float pdf = 0;
              for(int iangle = 0; iangle < DIFFUSE_ANGLE_NUM; iangle++)
              {
                  uint loc = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
                  vec3 directioni = normalize(DIFFUSE_DIRECTIONS[iangle]);
                  radtemp = voxelRads[loc].cumulated;
                  if(radtemp>0.05)
                  {
                      effeNum = effeNum + 1;
                      // rads = rads + radtemp;
                      rads = rads + radtemp * abs((directioni.y));
                      pdf = pdf + abs((directioni.y));

                  }
              }
              if (effeNum == 0) effeNum=1;
              if (pdf < EPSION_3) pdf = effeNum;
              rads = rads/pdf * PI;
              // rads = rads / effeNum * PI;
              // // rads = rads/(DIFFUSE_ANGLE_NUM / 2) * PI;
              
          }
          else
          {
            // iteration in diffuse
            int effeNum = 0;
            // float pdf = 0;
            for(int iangle = 0; iangle < DIFFUSE_ANGLE_NUM; iangle++)
            {
                uint loc = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
                vec3 directioni = normalize(DIFFUSE_DIRECTIONS[iangle]);
                radtemp = voxelRads[loc].cumulated;
                if(radtemp>0.05)
                {
                    effeNum = effeNum + 1;
                    rads = rads + radtemp;
                    // rads = rads + radtemp * abs(cos(directioni.y));
                    // pdf += abs(cos(directioni.y));

                }
            }
            if (effeNum == 0) effeNum=1;

            // rads = rads/pdf * 2 * PI;
            rads = rads / effeNum * 2 *PI;



            // rads = rads/DIFFUSE_ANGLE_NUM * 2 *PI * 0.5;
            // rads = rads/(DIFFUSE_ANGLE_NUM / 2);

            float lai = canopies[canopyId].lai;
            float p = calReCor(lai);
            float refl = spectralMaterials[spectralIdBase + kband_center].reflectance;
            float trans = spectralMaterials[spectralIdBase + kband_center].transmittance;
            float w = refl + trans;
            float s = (w - p* w) / (1 - p* w);
            float a = (1-w) / (1 - p *w); 
            // absorb = a;
          }

          rads = rads * absorb;
  
          // radSum = 100;
        // rads = effeNum;
          atomicAdd(voxelNetRads[bufferId0].diffuseVrad, rads, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
      }
// atomicStore(voxelNetRads[bufferId0].directVrad, radSum, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    }
}


