#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:require
#extension GL_EXT_shader_atomic_float: require 

#define VOXEL_LST_BIND_ININDEX
#define VOXELLST 1

#include "../bindinglayout.h"
#include "../parameters.h"
#include "../global.glsl"
#include "../settings.h"
#include "../functions.glsl"
#include "../nanovdb_info.glsl"
#include "../shade_state_voxel.glsl"

PtPayload        prd;
ShadowHitPayload shadow_payload;

#include "../traceray_comp.glsl"

layout(local_size_x = GROUP_SIZEX) in;

#define MAXBAND    25
#define NUM_VNIR 2001 
#define NUM_BAND 2002


float GammaR[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];
float GammaT[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];
// from solar direction to selected direction;
float GammaSR[DIFFUSE_ANGLE_NUM];
float GammaST[DIFFUSE_ANGLE_NUM];


// diffuse directions
void scattering_phase_function_diffuse()
{
  for(int iangle = 0;iangle < DIFFUSE_ANGLE_NUM; iangle++)
  {
    vec3 directioni = normalize(DIFFUSE_DIRECTIONS[iangle]);
    for(int jangle = 0;jangle < DIFFUSE_ANGLE_NUM; jangle++)
    {
      vec3 directionj = normalize(DIFFUSE_DIRECTIONS[jangle]);
      vec2 Gamma = scattering_phase_function_direct_XZY_paper(directioni,-directionj);
      GammaR[iangle*DIFFUSE_ANGLE_NUM + jangle] = Gamma.x;
      GammaT[iangle*DIFFUSE_ANGLE_NUM + jangle] = Gamma.y;
    }
  }
}

// diffuse directions
void scattering_phase_function_solar_diffuse()
{
  vec3 directioni = normalize(lightSet.direction);
  for(int jangle = 0;jangle < DIFFUSE_ANGLE_NUM; jangle++)
  {
      vec3 directionj = normalize(DIFFUSE_DIRECTIONS[jangle]);
      vec2 Gamma = scattering_phase_function_direct_XZY_paper(directioni,-directionj);
      GammaSR[jangle] = Gamma.x;
      GammaST[jangle] = Gamma.y;
  }
}


bool voxel_raytracing_diffuse(vec3 voxelPos0, uint bufferId0, NanoVDBLink nanoVDBLink,
 int kiter,int kband,float Esun,float Esky)
{
  // vec3 semiRange = setting.scale * setting.voxelSize/2.0;
  float scale = setting.scale;
  ivec3 semiRange = ivec3(floor(setting.voxelSize.x/2.0 + 0.5),
                            0,
                            floor(setting.voxelSize.z/2.0 + 0.5));       // voxel scene semiRange.
  // semiRange = vec3(0,0,0);
  // i:induced direction for the selected voxel; 0 original
  // j:induced direction for the traveled voxel;
  // s:solar direction
  vec3 directioni,directioni0,directionj,directionj0;
  vec3 directions = normalize(lightSet.direction);
  int bufferId,alignBufferId, meshId;
  uint spectralId,thermalId,canopyId;
  vec2 gammart;
  float alpha_voxel,alpha_toSolar,alpha_toVoxel;
  uint bioId,typeId;
  uint instanceId,lastInstanceId,alignInstanceId;
  uint bufferIdPlus0;
  ivec3 voxelId,alignVoxelId;
  float pl_toSolar,pl_toVoxel,refl,trans,emis,gamma,wavelength;
  float sunlitTemperature,sunlitRadiance,shadedTemperature,shadedRadiance,thermalRadiance;
  InstanceLink instanceLink;
  MeshLink meshLink;
  Canopy canopy;
  //ivec3 voxelId0 = voxelLinks[bufferId0].voxelId;
  uint instanceId0 = voxelLinks[bufferId0].instanceId;
  uint meshId0 = instanceLinks[instanceId0].meshId;
  uint typeId0 = meshLinks[meshId0].type;
  float density,G;
  bool isvegfirst = true;

  ivec3 voxelRes = ivec3(setting.voxelSize);
  float cosSolar = abs(normalize(lightSet.direction).y);
  ////////////////////////////////////////////////////////
  //  Iteration in difuse angle
  ////////////////////////////////////////////////////////
  for(uint iangle = 0; iangle < DIFFUSE_ANGLE_NUM; iangle++)
  {
    directioni0 = DIFFUSE_DIRECTIONS[iangle];
    directioni = normalize(directioni0);


    Ray ray = Ray(voxelPos0, directioni);
    // vec3 ffnormal0  = vec3(0,1,0);
    // ray.origin = OffsetRay(ray.origin, dot(ray.direction, ffnormal0) > 0 ? ffnormal0 : -ffnormal0);



    alpha_toSolar = 1.0;
    alpha_toVoxel = 1.0;
		voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced = 0.0;
    // if((typeId0 == TYPE_SOIL) && (directioni0.y < 0))
    // {
    //   continue;
    // }


    //----------------------------------
    //  uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
    // atomicAdd(voxelRads[index].induced,
    //     Esky,
    //     gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    //     continue;
    //---------------------------------------


    /////////////////////////////////////////////////////
    /// Iteration in travel step
    /////////////////////////////////////////////////////
    int kstep = 0;
    vec3 ffnormal;


    for(kstep = 0;kstep<=setting.maxStep;kstep++)
    { 
      alpha_voxel = 1.0;
      ClosestHit(ray,0.01);
      if(prd.hitT == INFINITY)
      {
        //////////////////////////////
        /// Atmospheric case
        /////////////////////////////

        // add save the sky contribution
        // sky contribution: lightSet.Rli*waveSets[kband].diffuse*0.001
        if(directioni0.y >= 0)
        {
           float skyrad = alpha_toVoxel*Esky;
          uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
          atomicAdd(voxelRads[index].induced,
              skyrad,
              gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
        }
        alpha_toVoxel = 0.001;
        break;
      }


      // float skyrad = 1;
      // uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
      // atomicAdd(voxelRads[index].induced,
      //     skyrad,
      //     gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
      //     break;

      // get hit information
      ShadeState sstate = GetShadeState(prd);
      voxelId = getVoxelIdSemi(sstate.position, semiRange, scale, directioni, alignVoxelId);
      bufferId = nanovdbGet(nanoVDBLink,voxelId);
      alignBufferId = nanovdbGet(nanoVDBLink, alignVoxelId);

      //////////////////////////////
      /// Trubid case
      /////////////////////////////
      if(bufferId >= 0)
      {
        // a valid voxel and get voxel information 
        // such as instanceId, typeId, spectralId, thermalId, canopyId
          instanceId = voxelLinks[bufferId].instanceId;
          InstanceLink instanceLink = instanceLinks[instanceId];
          meshId = instanceLink.meshId;
          MeshLink meshLink = meshLinks[meshId];
          spectralId = meshLink.spectralId;
          canopyId = meshLink.canopyId;
          bioId = meshLink.bioId;
          typeId = meshLink.type;

          if(typeId == TYPE_VEGETATION)
          {
            G = canopies[canopyId].G;
            // density determined by mesh/isntance or pixel scale?
            if(setting.islad < 1){
                density = canopies[canopyId].density;
            }else{         
                uint surf1DId = SurfFlatten(voxelId, voxelRes);
                density = lads[surf1DId]; 
            }
            float pathLength = Vector2Distance(sstate.position - sstate.lastPosition);
            alpha_voxel = exp(-density * G * pathLength * scale);
            alpha_toSolar = voxelDirs[bufferId].solar;

            // get the phase function for solar direction to induced direction 
            gammart.x = GammaSR[iangle];
            gammart.y = GammaST[iangle];
            sunlitTemperature = voxelTempes[bufferId].sunlit;
            shadedTemperature = voxelTempes[bufferId].shaded;
            /////////////////////////////////////////////////////
            /// Iteration in BAND
            /////////////////////////////////////////////////////

            
            // SPECTRAL
            trans = spectralMaterials[spectralId*NBAND+kband].transmittance;
            refl = spectralMaterials[spectralId*NBAND+kband].reflectance;
            emis = 1 - trans - refl;
            // THERMAL
            sunlitRadiance = Stefen_Boltzmann(sunlitTemperature,1);
            shadedRadiance = Stefen_Boltzmann(shadedTemperature,1);
            thermalRadiance = (1-alpha_toSolar)*shadedRadiance + alpha_toSolar*sunlitRadiance;
            // float gamma = abs(gammart.x)*(refl + trans) + abs(gammart.y)*trans;  
            float gamma = (gammart.x)*(refl + trans) + (gammart.y)*trans;  
            gamma = clamp(gamma,0,1);
            float radiance = 0;
            float lai = canopies[canopyId].lai;
            float p = calReCor(lai);
            float w = refl + trans;
            float s = (w - p* w) / (1 - p* w);
            float a = (1-w) / (1 - p *w); 
            // emis = a;

            //////////////////////////////
            /// Multiple case
            /////////////////////////////
            if(kiter > 0)
            {
              int effeNum = 0;
              for(int jangle=0;jangle<DIFFUSE_ANGLE_NUM;jangle++)
              {
                  float radiancej = voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+jangle].cumulated;
                  if (radiancej < EPSION_3) continue;
                  directionj0 = (DIFFUSE_DIRECTIONS[jangle]);   
                  gammart.x = GammaR[iangle*DIFFUSE_ANGLE_NUM+jangle];
                  gammart.y = GammaT[iangle*DIFFUSE_ANGLE_NUM+jangle];
                  gamma =   abs(gammart.x)*(refl + trans)+ abs(gammart.y)*trans;  
                  gamma = clamp(gamma,0,1);
                  radiance= radiance + radiancej * gamma* alpha_toVoxel*(1-alpha_voxel);  
                  effeNum ++;
              }
              if (effeNum == 0) effeNum = 1;
              // radiance = radiance/(DIFFUSE_ANGLE_NUM);
              radiance = radiance/effeNum;
            }
            //////////////////////////////
            // emitter
            /////////////////////////////
            // thermalRadiance = 100;
            radiance+= (thermalRadiance*(1-alpha_voxel)*emis* alpha_toVoxel);
            // radiance = shadedTemperature;
            //////////////////////////////
            /// Solar 
            /////////////////////////////
            // radiance += (alpha_toSolar * gamma * Esun/cosSolar * alpha_toVoxel *(1-alpha_voxel)); 
            // radiance += (alpha_toSolar * gamma * Esun * alpha_toVoxel *(1-alpha_voxel));   
            //////////////////////////////
            /// Save back
            /////////////////////////////
            atomicAdd(voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced,radiance,
                gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
          alpha_toVoxel = alpha_toVoxel * alpha_voxel;
          if(alpha_toVoxel < 0.01) break; 
        } // veg
      } // bufferId
      if (alignBufferId >= 0)
      {
          //////////////////////////////
          /// facet case
          /////////////////////////////
          instanceId = voxelLinks[alignBufferId].instanceId;
          meshId = instanceLinks[instanceId].meshId;
          typeId = meshLinks[meshId].type;
          canopyId = meshLinks[meshId].canopyId;
          spectralId = meshLinks[meshId].spectralId;
          thermalId = meshLinks[meshId].thermalId;


          if(typeId == TYPE_VEGETATION){
            //// do nothing
            // ray = Ray(sstate.position,directioni);
            // ffnormal  = sstate.normal;
            // ray.origin = OffsetRay(ray.origin, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
            // continue;
          }

          if(typeId == TYPE_BUILDING)
          {
            int faceId = getFaceIdSimple(sstate.position,semiRange,alignVoxelId);
            alignBufferId = alignBufferId + faceId;
            // alignVoxelId = alignVoxelId + faceId; ???
          }

          if(typeId == TYPE_BUILDING || typeId == TYPE_SOIL){
            
            uint spectralIdBase = spectralId*NBAND;
            alpha_toSolar = voxelDirs[alignBufferId].solar;
            vec3 wo = directioni;  // FROM SELECTED VOXEL OUT TO HIT FACET  
            vec3 wi = lightSet.direction; // FROM SELECTED VOXEL OUT TO SOLAR
            vec3 ffnormal = sstate.normal;
            bool inSameSides = IsSameSide(wo,wi,ffnormal);

            // THERMAL
            sunlitTemperature = voxelTempes[alignBufferId].sunlit;
            shadedTemperature = voxelTempes[alignBufferId].shaded;
            float radiance=0;

            
            // SPECTRAL
            trans = spectralMaterials[spectralId*NBAND+kband].transmittance;
            refl = spectralMaterials[spectralId*NBAND+kband].reflectance;
            emis = 1 - trans - refl;

            sunlitRadiance = Stefen_Boltzmann(sunlitTemperature,1);
            shadedRadiance = Stefen_Boltzmann(shadedTemperature,1);
            thermalRadiance = (1-alpha_toSolar)*shadedRadiance + alpha_toSolar*sunlitRadiance;
            //////////////////////////////
            /// Multiple case
            /////////////////////////////
            if(kiter > 0)
            {
              int effeNum = 0;
              for(int jangle=0;jangle<DIFFUSE_ANGLE_NUM;jangle++)
              {
                  directionj0 = (DIFFUSE_DIRECTIONS[jangle]);
                  bool inSameSide = IsSameSide(directioni,directionj0,ffnormal);
                  if(!inSameSide) continue;
                  float radiancej = voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].cumulated;
                  if (radiancej < EPSION_3) continue;
                  radiance= radiance + radiancej * refl* alpha_toVoxel;  
                  effeNum ++;
              }
              if (effeNum == 0) effeNum = 1;
              // radiance = radiance/(DIFFUSE_ANGLE_NUM/2);
              radiance = radiance/effeNum;
            }
            
            ////////////////////////////////
            // SOLAR CASE
            ///////////////////////////////
            // if(inSameSides)
            // {
              // radiance += (refl * Esun * alpha_toSolar * alpha_toVoxel);
            // }
            // ////////////////////////////////
            // //emitter
            // ////////////////////////////////
            radiance+= (thermalRadiance * emis * alpha_toVoxel);
            //////////////////////////////
            /// Save back
            /////////////////////////////
            atomicAdd(voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced,radiance,
                gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);

            alpha_toVoxel = 0;
            break;
          }
      }// alignbufferId

      ray = Ray(sstate.position,directioni);
      ffnormal  = sstate.normal;
      ray.origin = OffsetRay(ray.origin, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
    } // step

    if((alpha_toVoxel > 0.05))
    {
        float skyrad = alpha_toVoxel*Esky;
        //skyrad = 0.5;
        uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
        atomicAdd(voxelRads[index].induced,
            skyrad,
            gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    }
  } // angle
  return false;
}


void main()
{
    //------------------------------------------------------------
    // Initialization for the position and SSBO index
    //------------------------------------------------------------
    // get bufferId, voxelId, instanceId and typeId
    uint bufferId0 = (gl_GlobalInvocationID.x);
    ivec3 voxelId0 = voxelLinks[bufferId0].voxelId;
      if(voxelLinks[bufferId0].isValid==0) return;
      
    uint instanceId0 = voxelLinks[bufferId0].instanceId;
    uint meshId0 = instanceLinks[instanceId0].meshId;

    InstanceLink instanceLink0 = instanceLinks[instanceId0];
    MeshLink meshLink0 = meshLinks[meshId0];
    uint typeId0 = meshLink0.type;
    uint spectralId0 = meshLink0.spectralId;
    vec3 ffnormal0 = vec3(0,1,0);


    uint	canopyId = meshLinks[meshId0].canopyId;
    int faceId = voxelLinks[bufferId0].faceId;

    // if(primId0 - faceid0*10 == 0) return; 


    // if(primId0 == 0) {ffnormal0 = vec3(0,0,0); }
    // atomicAdd(voxelNetRads[bufferId0].diffuseTrad, primId0, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    // return;
    // Get nanoVDBLink: from voxelId to bufferId
    NanoVDBLink nanoVDBLink = nanovdbInit();
    // get center position of a voxel
    vec3 semiRange = vec3(floor(setting.voxelSize.x/2.0+0.5),0,floor(setting.voxelSize.z/2.0+0.5));
    vec3 voxelPos0 = vec3(voxelId0.x-semiRange.x,
                          voxelId0.y,
                          voxelId0.z -semiRange.z); 
    getFacetIdPos(faceId,  voxelPos0);

    float Rin = ubom.meteo.Rin;               // measurement height 
    float Rli = ubom.meteo.Rli;               // wind speed

    // reset the voxelRads in VNIR band
    // for(uint kband=NUM_VNIR;kband < NUM_BAND;kband++)
    //   for(uint iangle=0;iangle < DIFFUSE_ANGLE_NUM;iangle++)
    //   {
    //     uint index = bufferId0*32*2162+kband*32+iangle;
    //     voxelRads[index].cumulated=0.0;
    //   }

    //------------------------------------------------------------
    // An iteration process for diffuse scattering function
    //------------------------------------------------------------
    // pre-calcuation Gamma 
    scattering_phase_function_diffuse();
    scattering_phase_function_solar_diffuse(); 
    
    voxelNetRads[bufferId0].diffuseTrad = 0 ;

    int kband_start = 0, kband_end = 0;
    // int kstep = setting.bandTstep;
    int kbandj = NUM_VNIR;
    int kband_center = NUM_VNIR;


    float wavelength = atomConds[kbandj].wavelength;
    float Esun = 0;
    float Esky = Rli;

        for(int kiter=0;kiter< 3;kiter++)
        {
            voxel_raytracing_diffuse(voxelPos0, bufferId0, nanoVDBLink, kiter,kband_center,Esun,Esky);
            groupMemoryBarrier();  
            barrier();

            for(uint iangle=0;iangle < DIFFUSE_ANGLE_NUM;iangle++)
            {
                uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
                voxelRads[index].cumulated = voxelRads[index].induced;
            }
        }// for iteration

    //------------------------------------------------------------
    // accumulated incident radiation to four components: direct/diffuse VNIN/TIR radiation
    //------------------------------------------------------------

        float rads=0,radtemp = 0,absorb = 1.0;
        // iteration in diffuse angle
        int effeNum = 0;
        for(uint iangle=0;iangle < DIFFUSE_ANGLE_NUM;iangle++)
        {

           vec3 directioni0 = DIFFUSE_DIRECTIONS[iangle];
           vec3  directioni = normalize(directioni0);
           float abc = cross0(directioni0,ffnormal0);
           if(abc <=0) {continue;}
            uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
            radtemp = voxelRads[index].cumulated;
            if(radtemp>1)
            {
              effeNum = effeNum + 1;
              rads = rads + radtemp;
            }


        }// for iteration
        if (effeNum < 1) effeNum=1;
        uint spectralIdBase = spectralId0*NBAND;
        absorb = 1- spectralMaterials[spectralIdBase+kband_center].transmittance - 
                    spectralMaterials[spectralIdBase+kband_center].reflectance;
        if(effeNum >0){
          if (typeId0 == TYPE_SOIL || typeId0 == TYPE_BUILDING)
          {
              rads = rads/effeNum;
              // rads = rads/(DIFFUSE_ANGLE_NUM / 2.0);
          }
          else
          {
            rads = rads/effeNum;   
            // rads = rads/DIFFUSE_ANGLE_NUM;

            float lai = canopies[canopyId].lai;
            float p = calReCor(lai);
            float refl = spectralMaterials[spectralIdBase + kband_center].reflectance;
            float trans = spectralMaterials[spectralIdBase + kband_center].transmittance;
            float w = refl + trans;
            float s = (w - p* w) / (1 - p* w);
            float a = (1-w) / (1 - p *w); 
            // absorb = a;
          }
        }
        
        rads = rads *absorb;

        atomicStore(voxelNetRads[bufferId0].diffuseTrad, rads, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    //}// for band

}