#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#define VOXELLST
#include "../bindinglayout.h"
#include "../global.glsl"

layout(local_size_x = GROUP_SIZEX) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    uint count = uint(fluidParameters.grid.x * fluidParameters.grid.y
                      * fluidParameters.grid.z);
    if (index >= count || fluidParameters.grid.w == 0) return;

    uint first = index * 19u;
    for (uint direction = 0u; direction < 19u; ++direction) {
        fluidLbmA[first + direction] = fluidLbmB[first + direction];
    }
    fluidVelocityA[index] = fluidVelocityB[index];
    fluidScalarA[index] = fluidScalarB[index];
}
