#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:require
#extension GL_EXT_shader_atomic_float: require 


#define VOXEL_LST_BIND_ININDEX
#define VOXELLST 

#include "../bindinglayout.h"
#include "../parameters.h"
#include "../global.glsl"
#include "../functions.glsl"
#include "../nanovdb_info.glsl"

layout(local_size_x = GROUP_SIZEXY,local_size_y = GROUP_SIZEXY) in;

void main()
{
    //------------------------------------------------------------
    // Initialization for the position and SSBO index
    //------------------------------------------------------------
    ivec3 voxelId = ivec3(gl_GlobalInvocationID.x, 0, gl_GlobalInvocationID.y);
    //voxelRes: voxel number in 3 dimentions
    ivec3 voxelRes = ivec3(setting.voxelSize);
    int surf1DId = SurfFlatten(voxelId,voxelRes);
    // Get nanoVDBLink: from voxelId to bufferId
    NanoVDBLink nanoVDBLink = nanovdbInit();
    

    //-------------------------
    // various parameters index
    //-------------------------
    uint spectralId,spectralId0;  // spectral property index of a voxel
    uint canopyId,canopyId0;      // canopy structure of a voxel
    uint instanceId0, instanceId,lastInstanceId=-1; // instance information of a voxel
    uint aeroId,aeroId0;          // aerodynamic property index of a voxel
    uint typeId,typeId0;          // voxel type: vegetation, soil...
    uint bufferId,bioId;
    int bufferId0 = nanovdbGet(nanoVDBLink,voxelId);
    if(bufferId0 < 0) 
    {
        return;
    }
    //-----------------------------------------------   
    // input from CPU parameter
    //-----------------------------------------------
    instanceId0 = voxelLinks[bufferId0].instanceId;
    aeroId0 = voxelLinks[bufferId0].aeroId;
    // VoxelInstanceLink instanceLink0 = instanceLinks[instanceId0];
    InstanceLink instancelink0 = instanceLinks[instanceId0];
    MeshLink meshLink0 = meshLinks[instancelink0.meshId];
    spectralId = meshLink0.spectralId;
    canopyId = meshLink0.canopyId;                                                       
    bioId = meshLink0.bioId;
    typeId = meshLink0.type;
    if(typeId == TYPE_NULL) return;
    
    // toppest voxel height
    // float hvmax = surfLs[surf1DId].hvmax;
    AeroCond aeroCond = aeroConds[aeroId];
    float hvmax = aeroCond.hc_veg;

  //  hvmax = 15;

    
    float hcmax = 1.0 * hvmax * setting.scale;
    int voxelMaxY = int(hvmax);
    // float Ltemp = bufferId0;
    // float Ptemp = surf1DId;
    // float xtemp = gl_GlobalInvocationID.x;
    // float ytemp = gl_GlobalInvocationID.y;
    // atomicStore(surfLs[surf1DId].hvmax,xtemp,gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    // atomicStore(surfLs[surf1DId].laimax,ytemp,gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    // atomicStore(surfLs[surf1DId].ustar,Ptemp,gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    // atomicStore(surfLs[surf1DId].L,Ltemp,gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    // return;

    //-----------------------------------------------   
    // update L
    //-----------------------------------------------
    float Hsum = 0;
    float Ssum = 0;
    for(int hi = 0;hi<=voxelMaxY;hi++)
    {
        voxelId.y = hi;
        bufferId = nanovdbGet(nanoVDBLink,voxelId);
        if(bufferId<0) continue;
        Hsum = Hsum + voxelHeatFlux[bufferId].Hsunlit*voxelDirs[bufferId].solar + 
            (1-voxelDirs[bufferId].solar)*voxelHeatFlux[bufferId].Hshaded;
        Ssum = Ssum + 1;
    }
    float H = 1.0*Hsum/Ssum;
    float L = -RHOA * CP * pow(aeroCond.ustar, 3) * (ubom.meteo.Ta + 273.15)/(KAPPA * GEARTH * H);
    //-----------------------------------------------   
    // save back
    //-----------------------------------------------
    //L = 1;
    // if(isnan(L)) L = -1;
    // atomicStore(aeroConds[aeroId].L, L, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsRelaxed);
 

}


